### ISSUE TITLE
Test results are not sent to the local Report Portal server

### ISSUE THREAD

**Issue by IvanSmolin** [reportportal/agent-net-xunit#2]
**1.** Download zip archive from the "Releases" tab and extract it into the folder with "xunit.console.exe" file
**2.** Correctly configure connection with Report Portal server in "ReportPortal.config.json" file
**3.** Run your tests on the command line

**Actual result:** An unexpected error occurred on a send.
**Expected result:** The test results are successfully sent to the server.

**LOGS:**
System.AggregateException: One or more errors occurred. ---> System.Exception: Cannot finish launch due starting launch failed. ---> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.RetryWithExponentialBackoffHttpClientHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ReportPortal.Client.RetryWithExponentialBackoffHttpClientHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.Service.<StartLaunchAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass12_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass17_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ReportPortal.XUnitReporter.ReportPortalReporterMessageHandler.TestAssemblyExecutionFinished(MessageHandlerArgs`1 args) in C:\projects\agent-net-xunit\ReportPortal.XUnitReporter\ReportPortalMessageHandler.Assembly.cs:line 58
---> (Inner Exception #0) System.Exception: Cannot finish launch due starting launch failed. ---> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.RetryWithExponentialBackoffHttpClientHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ReportPortal.Client.RetryWithExponentialBackoffHttpClientHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.Service.<StartLaunchAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass12_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass17_0.<<Finish>b__1>d.MoveNext()<---

**Comment by nvborisenko** [comment]
Please verify 'url' property in config. Seems you are trying to use https, but should be http.
