### ISSUE TITLE
Exception is thrown when running tests using dotnet test and RP host is unavailable 

### ISSUE THREAD

**Issue by egorsolovyev98** [reportportal/agent-net-xunit#24]
Hi all,

When I run tests using **dotnet test** command and RP host is unavailable, I have the error below. Is there a possibility to configure this error to not be thrown or to be skipped? 
Originally it occurred during CI / CD process, one of the scripts returned code 1 when the error above is returned.

ReportPortal.XUnit Version="2.4.4"
xunit.runner.visualstudio Version="2.4.5"

```
[xUnit.net 00:00:27.28] System.Exception: Cannot finish launch due starting launch failed.
 ---> System.AggregateException: One or more errors occurred. ('Invocation of 'Starting new ' Some Project Name' launch...' has not been finished.)
 ---> RetryExecutionException: 'Invocation of 'Starting new ' Some Project Name' launch...' has not been finished.
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func 1 func, Action 1 beforeNextAttempt, IStatisticsCounter statisticsCounter, String logicalOperationName)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass23_0.<<Start>b__0>d.MoveNext()
 ---> (Inner Exception #0) System.Net.Http.HttpRequestException: 'Starting new ' Some Project Name' launch...' threw an exception. Next attempt in 8 second(s).
 ---> System.Net.Http.HttpRequestException: No such host is known. (yourInvalidUrl.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation 1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter 1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceLaunchResource.StartAsync(StartLaunchRequest request, CancellationToken cancellationToken)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func 1 func, Action 1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter, String logicalOperationName)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func 1 func, Action 1 beforeNextAttempt, IStatisticsCounter statisticsCounter, String logicalOperationName)
   --- End of inner exception stack trace --- <---
   
    ---> (Inner Exception #1) System.Net.Http.HttpRequestException: 'Starting new ' Some Project Name' launch...' threw an exception. Next attempt in 16 second(s).
 ---> System.Net.Http.HttpRequestException: No such host is known. (yourInvalidUrl.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation 1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter 1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceLaunchResource.StartAsync(StartLaunchRequest request, CancellationToken cancellationToken)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func 1 func, Action 1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter, String logicalOperationName)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func 1 func, Action 1 beforeNextAttempt, IStatisticsCounter statisticsCounter, String logicalOperationName)
   --- End of inner exception stack trace --- <---

 ---> (Inner Exception #2) System.Net.Http.HttpRequestException: 'Starting new ' Some Project Name' launch...' threw an exception. Limit of retries has been reached.
 ---> System.Net.Http.HttpRequestException: No such host is known. (yourInvalidUrl.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation 1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter 1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceLaunchResource.StartAsync(StartLaunchRequest request, CancellationToken cancellationToken)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func 1 func, Action 1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter, String logicalOperationName)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func 1 func, Action 1 beforeNextAttempt, IStatisticsCounter statisticsCounter, String logicalOperationName)
   --- End of inner exception stack trace --- <---

   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass28_0.<<Finish>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.XUnitReporter.ReportPortalReporterMessageHandler.TestAssemblyExecutionFinished(MessageHandlerArgs 1 args) in C:\projects\agent-net-xunit\src\ReportPortal.XUnitReporter\ReportPortalMessageHandler.Assembly.cs:line 64
```

Config file:
```
{
  "$schema": "https://raw.githubusercontent.com/reportportal/agent-net-xunit/master/src/ReportPortal.XUnitReporter/ReportPortal.config.schema",
  "enabled": true,
  "server": {
    "url": "https://invalidUrl.com",
    "project": "someProject",
    "ignoreSslErrors": true,
    "authentication": {
      "uuid": "your-uuid"
    }
  },
  "launch": {
    "name": "name",
    "description": "description",
    "debugMode": true,
    "attributes": [
      "branch: local run",
      "release: false"
    ]
  }
}
```

**Comment by nvborisenko** [comment]
https://github.com/reportportal/agent-net-xunit/blob/e37678d55605ea62373e2818e063d54415bc7496/src/ReportPortal.XUnitReporter/ReportPortalMessageHandler.Assembly.cs#L72C17-L72C17

Based on code what I see, looks like xunit runner treats logged errors as real errors and returns non-zero exit code.
Actions to do:
- Check that statement is true
- Replace it with `LogWarning`

**Comment by egorsolovyev98** [comment]
@nvborisenko you were right. Tested it with `LogWarning` - no such error any more

**Comment by nvborisenko** [comment]
And exit code is 0? `dotnet test` is happy?

**Comment by egorsolovyev98** [comment]
yep, exit code was 0 after the fix

**Comment by nvborisenko** [comment]
Thanks, v2.4.5 has been released.
